apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-public-endpoint
  annotations:
    policies.kyverno.io/category: Terraform - EKS Auto Mode Best Practices
    policies.kyverno.io/description: Public endpoint for the EKS cluster should be disabled
    policies.kyverno.io/severity: critical
    policies.kyverno.io/subject: TerraformPlan
    policies.kyverno.io/title: Check Public Endpoint
spec:
  evaluation:
    mode: JSON
  variables:
    - name: eksChanges
      expression: >- 
        object.resource_changes.filter(rc, rc.type == "aws_eks_cluster" && 
          rc.change.actions.exists(a, a == 'create' || a == 'update'))
  validations:
  - message: The public endpoint for the EKS cluster must be disabled. Set `endpoint_public_access` to `false` in the `vpc_config` block.
    expression: >-
      variables.eksChanges.all(rc,
        rc.change.after.vpc_config.all(vpc, vpc.endpoint_public_access == false))